1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a vector with values ranging from 10 to 49.
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.


In [1]:
import numpy as np

## 1. Create a null vector of size 10 but the fifth value which is 1.

In [6]:
arrayx = np.arange(10)
arrayx[4]= 1
arrayx


array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

## 2. Create a vector with values ranging from 10 to 49.

In [7]:
array1 = np.arange(10,50)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
mat1 = np.arange(9).reshape(3,3)
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
array2 = [1,2,0,0,4,0]
np.nonzero(array2)

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [19]:
mat10 = (np.random.randn(10,10))
print(mat10)
print(mat10.min())
print(mat10.max())


-2.1305808146603056
2.370473360106554


## 6. Create a random vector of size 30 and find the mean value.


In [28]:
vec = np.random.random(30)

In [29]:
vec

array([0.09192602, 0.90758379, 0.12083571, 0.21225063, 0.20495759,
       0.48623183, 0.53463077, 0.31533379, 0.06282363, 0.34356939,
       0.42712939, 0.27553643, 0.00285559, 0.77700899, 0.67961065,
       0.71470677, 0.88455825, 0.12720827, 0.05114632, 0.81833212,
       0.68189068, 0.1881393 , 0.59518057, 0.92515179, 0.60133483,
       0.28873101, 0.81859923, 0.51062567, 0.78142646, 0.15463641])

In [30]:
vec.mean()

0.45279839632237245